<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Questions for Lesson 1: Parts of My Body (36 questions, 6 per part)
        $questionsLesson1 = [
            // Part 1: Head & Face (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] What illness makes your stomach feel bad?',
                'prompt_type' => 'text',
                'options' => json_encode(['Headache', 'Stomachache', 'Toothache', 'Fever']),
                'correct_answers' => json_encode(['Stomachache']),
                'hint' => 'The pain in your stomach area',
                'position' => 1,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'select_image',
                'prompt' => '[Part 1] Select the image that shows "Arm"',
                'prompt_type' => 'text',
                'options' => json_encode(['body_parts/part1/arm.jpg', 'body_parts/part1/leg.jpg', 'body_parts/part1/hand.jpg', 'body_parts/part1/foot.jpg']),
                'correct_answers' => json_encode(['body_parts/part1/arm.jpg']),
                'hint' => 'The body part that connects the shoulder and the hand',
                'position' => 2,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] What do you have when your body feels very hot?',
                'prompt_type' => 'text',
                'options' => json_encode(['Cold', 'Fever', 'Stomachache', 'Toothache']),
                'correct_answers' => json_encode(['Fever']),
                'hint' => 'When your body temperature is higher than normal',
                'position' => 3,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] Which part helps you to walk?',
                'prompt_type' => 'text',
                'options' => json_encode(['Arms', 'Legs', 'Neck', 'Back']),
                'correct_answers' => json_encode(['Legs']),
                'hint' => 'The limbs that help you move around',
                'position' => 4,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] We can taste food with our...',
                'prompt_type' => 'text',
                'options' => json_encode(['Ears', 'Eyes', 'Tongue', 'Nose']),
                'correct_answers' => json_encode(['Tongue']),
                'hint' => 'The organ in your mouth that senses taste',
                'position' => 5,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] Where are your legs?',
                'prompt_type' => 'text',
                'options' => json_encode(['Below your body', 'Above your head', 'On your face', 'Between your fingers']),
                'correct_answers' => json_encode(['Below your body']),
                'hint' => 'Think about where your legs are located on your body',
                'position' => 6,
                'is_advanced' => false,
            ],

            // Part 2: Limbs (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2] What happens when you have a cold?',
                'prompt_type' => 'text',
                'options' => json_encode(['Your head hurts', 'Your nose runs and you sneeze', 'Your stomach hurts', 'Your tooth hurts']),
                'correct_answers' => json_encode(['Your nose runs and you sneeze']),
                'hint' => 'Common symptoms of a cold',
                'position' => 7,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2] Which part is on top of your body?',
                'prompt_type' => 'text',
                'options' => json_encode(['Head', 'Foot', 'Knee', 'Elbow']),
                'correct_answers' => json_encode(['Head']),
                'hint' => 'Think about which body part is at the highest point',
                'position' => 8,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2] Kimmy uses her ... to chew the meatball',
                'prompt_type' => 'text',
                'options' => json_encode(['Leg', 'Teeth', 'Nose', 'Head']),
                'correct_answers' => json_encode(['Teeth']),
                'hint' => 'What do we use to break down food in our mouth?',
                'position' => 9,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2] What do we call the illness that makes you sound like "uhuk, uhuk"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Toothache', 'Cough', 'Fever', 'Stomachache']),
                'correct_answers' => json_encode(['Cough']),
                'hint' => 'The sound you make when clearing your throat or lungs',
                'position' => 10,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'select_image',
                'prompt' => '[Part 2] Select the image that shows "Mouth"',
                'prompt_type' => 'text',
                'options' => json_encode(['body_parts/part2/eye.jpg', 'body_parts/part2/ear.jpg', 'body_parts/part2/nose.jpg', 'body_parts/part2/mouth.jpg']),
                'correct_answers' => json_encode(['body_parts/part2/mouth.jpg']),
                'hint' => 'The facial part for speaking and eating',
                'position' => 11,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'select_image',
                'prompt' => '[Part 2] Select the image that shows "Shoulder"',
                'prompt_type' => 'text',
                'options' => json_encode(['body_parts/part2/shoulder.jpg', 'body_parts/part2/arm.jpg', 'body_parts/part2/back.jpg', 'body_parts/part2/neck.jpg']),
                'correct_answers' => json_encode(['body_parts/part2/shoulder.jpg']),
                'hint' => 'The body part that connects the arm with the body',
                'position' => 12,
                'is_advanced' => false,
            ],

            // Part 3: Body Parts Detail (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 3] Which English word is correct for "rambut"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Hair', 'Head', 'Skin', 'Face']),
                'correct_answers' => json_encode(['Hair']),
                'hint' => 'The fibers that grow on the head',
                'position' => 13,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'select_image',
                'prompt' => '[Part 3] Select the image that shows "Hand"',
                'prompt_type' => 'text',
                'options' => json_encode(['body_parts/part3/arm.jpg', 'body_parts/part3/hand.jpg', 'body_parts/part3/leg.jpg', 'body_parts/part3/foot.jpg']),
                'correct_answers' => json_encode(['body_parts/part3/hand.jpg']),
                'hint' => 'The body part at the end of the arm with fingers',
                'position' => 14,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'image_choice',
                'prompt' => '[Part 3] What is the English name for this body part?',
                'prompt_type' => 'image',
                'image_url' => 'body_parts/part3/foot.jpg',
                'options' => json_encode(['Hand', 'Arm', 'Foot', 'Leg']),
                'correct_answers' => json_encode(['Foot']),
                'hint' => 'The end part of the leg that touches the floor',
                'position' => 15,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 3] Translate to English: "Jari kaki"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Toe', 'Toes']),
                'hint' => 'The small parts at the end of the foot',
                'position' => 16,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 3] Which English word is correct for "leher"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Neck', 'Shoulder', 'Chest', 'Back']),
                'correct_answers' => json_encode(['Neck']),
                'hint' => 'The body part that connects the head with the body',
                'position' => 17,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 3] Translate to English: "Punggung"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Back']),
                'hint' => 'The rear part of the body from the neck to the waist',
                'position' => 18,
                'is_advanced' => false,
            ],

            // Part 4: Internal Organs (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4] Which English word is correct for "jantung"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Heart', 'Lung', 'Brain', 'Liver']),
                'correct_answers' => json_encode(['Heart']),
                'hint' => 'The organ that pumps blood throughout the body',
                'position' => 19,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'image_choice',
                'prompt' => '[Part 4] What is the English name for this organ?',
                'prompt_type' => 'image',
                'image_url' => 'body_parts/part4/brain.jpg',
                'options' => json_encode(['Brain', 'Heart', 'Lung', 'Stomach']),
                'correct_answers' => json_encode(['Brain']),
                'hint' => 'The organ for thinking inside the head',
                'position' => 20,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 4][Advanced] Translate to English: "Paru-paru"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Lungs', 'Lung']),
                'hint' => 'The organs for breathing',
                'position' => 21,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4] What is the English word for "perut"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Stomach', 'Chest', 'Liver', 'Heart']),
                'correct_answers' => json_encode(['Stomach']),
                'hint' => 'The organ for digesting food',
                'position' => 22,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 4][Advanced] Translate to English: "Hati"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Liver']),
                'hint' => 'An important organ for filtering toxins',
                'position' => 23,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4] Which English word is correct for "ginjal"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Kidney', 'Liver', 'Heart', 'Brain']),
                'correct_answers' => json_encode(['Kidney']),
                'hint' => 'The organ for filtering blood',
                'position' => 24,
                'is_advanced' => false,
            ],

            // Part 5: Body Movements (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5][Advanced] What is the English for "menekuk lutut"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Bend knee', 'Move leg', 'Turn foot', 'Stretch leg']),
                'correct_answers' => json_encode(['Bend knee']),
                'hint' => 'The movement of folding the leg part',
                'position' => 25,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 5] Translate to English: "Mengangkat tangan"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Raise hand', 'Lift hand']),
                'hint' => 'The hand movement upward',
                'position' => 26,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5][Advanced] Which is correct for "mengedipkan mata"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Blink eyes', 'Close eyes', 'Open eyes', 'Move eyes']),
                'correct_answers' => json_encode(['Blink eyes']),
                'hint' => 'The movement of closing and opening eyes quickly',
                'position' => 27,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 5] Translate to English: "Membuka mulut"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Open mouth']),
                'hint' => 'The movement of having the mouth open',
                'position' => 28,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5][Advanced] What is the English for "menggerakkan jari"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Move fingers', 'Touch fingers', 'Use fingers', 'Bend fingers']),
                'correct_answers' => json_encode(['Move fingers']),
                'hint' => 'The movement of the fingers',
                'position' => 29,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 5] Translate to English: "Memutar kepala"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Turn head', 'Rotate head']),
                'hint' => 'The movement of rotating the head',
                'position' => 30,
                'is_advanced' => false,
            ],

            // Part 6: Body Characteristics (6 questions)
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6][Advanced] Which is correct for "kulit"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Skin', 'Surface', 'Cover', 'Layer']),
                'correct_answers' => json_encode(['Skin']),
                'hint' => 'The outer layer of the body',
                'position' => 31,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Tulang rusuk"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Rib', 'Ribs']),
                'hint' => 'The bones that protect organs in the chest',
                'position' => 32,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6] What is the English for "otot"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Muscle', 'Flesh', 'Tissue', 'Bone']),
                'correct_answers' => json_encode(['Muscle']),
                'hint' => 'The body part for movement',
                'position' => 33,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Pembuluh darah"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Blood vessel', 'Blood vessels']),
                'hint' => 'The channels for blood flow',
                'position' => 34,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 1,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6] Which is correct for "tulang"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Bone', 'Skeleton', 'Joint', 'Muscle']),
                'correct_answers' => json_encode(['Bone']),
                'hint' => 'The hard part inside the body',
                'position' => 35,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 1,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Sendi"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Joint']),
                'hint' => 'The place where bones meet and move',
                'position' => 36,
                'is_advanced' => true,
            ],
        ];

        // Questions for Lesson 2: Kinds of Illness (36 questions, 6 per part)
        $questionsLesson2 = [
            // Part 1: Common Symptoms (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] What is the English word for "sakit kepala"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Headache', 'Stomachache', 'Toothache', 'Backache']),
                'correct_answers' => json_encode(['Headache']),
                'hint' => 'The pain in the head (head + ache)',
                'position' => 1,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'image_choice',
                'prompt' => '[Part 1] What is the English name for this illness?',
                'prompt_type' => 'image',
                'image_url' => 'illness/part1/fever.jpg',
                'options' => json_encode(['Fever', 'Cold', 'Cough', 'Flu']),
                'correct_answers' => json_encode(['Fever']),
                'hint' => 'When the body temperature rises and you feel hot',
                'position' => 2,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'select_image',
                'prompt' => '[Part 1] Select the image that shows "Cough"',
                'prompt_type' => 'text',
                'options' => json_encode(['illness/part1/cough.jpg', 'illness/part1/cold.jpg', 'illness/part1/fever.jpg', 'illness/part1/headache.jpg']),
                'correct_answers' => json_encode(['illness/part1/cough.jpg']),
                'hint' => 'When air comes out of the lungs forcefully',
                'position' => 3,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 1] Translate to English: "Sakit perut"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Stomachache', 'Stomach ache']),
                'hint' => 'The pain in the stomach (stomach + ache)',
                'position' => 4,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 1] What is the English word for "bersin"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Sneeze', 'Cough', 'Yawn', 'Hiccup']),
                'correct_answers' => json_encode(['Sneeze']),
                'hint' => 'The bodily reaction when the nose is irritated, with a "hachoo!" sound',
                'position' => 5,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 1][Advanced] Translate to English: "Saya merasa tidak enak badan"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['I feel unwell', 'I feel sick', 'I don\'t feel well']),
                'hint' => 'A general expression when feeling unwell',
                'position' => 6,
                'is_advanced' => true,
            ],

            // Part 2: Specific Pains (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2][Advanced] What is the English word for "pilek"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Fever', 'Cold', 'Cough', 'Flu']),
                'correct_answers' => json_encode(['Cold']),
                'hint' => 'When your nose is stuffy and runny',
                'position' => 7,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'image_choice',
                'prompt' => '[Part 2] What is the English name for this illness?',
                'prompt_type' => 'image',
                'image_url' => 'illness/part2/flu.jpg',
                'options' => json_encode(['Fever', 'Cold', 'Cough', 'Flu']),
                'correct_answers' => json_encode(['Flu']),
                'hint' => 'It\'s like a cold but worse',
                'position' => 8,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'select_image',
                'prompt' => '[Part 2] Select the image that shows "Toothache"',
                'prompt_type' => 'text',
                'options' => json_encode(['illness/part2/toothache.jpg', 'illness/part2/headache.jpg', 'illness/part2/backache.jpg', 'illness/part2/stomachache.jpg']),
                'correct_answers' => json_encode(['illness/part2/toothache.jpg']),
                'hint' => 'The pain in the tooth',
                'position' => 9,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 2] Translate to English: "Sakit punggung"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Backache', 'Back pain']),
                'hint' => 'The pain in the back (back + ache)',
                'position' => 10,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 2] What is the English word for "sakit tenggorokan"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Sore throat', 'Throat pain', 'Neck ache', 'Mouth pain']),
                'correct_answers' => json_encode(['Sore throat']),
                'hint' => 'The pain or irritation in the throat',
                'position' => 11,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 2] Translate to English: "Sakit telinga"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Earache', 'Ear pain']),
                'hint' => 'The pain in the ear (ear + ache)',
                'position' => 12,
                'is_advanced' => false,
            ],

            // Part 3: Medical Situations (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 3] What is the English word for "pusing"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Dizziness', 'Fatigue', 'Nausea', 'Fever']),
                'correct_answers' => json_encode(['Dizziness']),
                'hint' => 'The feeling of your head spinning and not balanced',
                'position' => 13,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'image_choice',
                'prompt' => '[Part 3] What is the English name for this illness?',
                'prompt_type' => 'image',
                'image_url' => 'illness/part3/sore_throat.jpg',
                'options' => json_encode(['Sore throat', 'Cough', 'Cold', 'Fever']),
                'correct_answers' => json_encode(['Sore throat']),
                'hint' => 'The pain in the throat',
                'position' => 14,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 3] Select the correct sentence in English:',
                'prompt_type' => 'text',
                'options' => json_encode(['I have a fever', 'I am a fever', 'I fever', 'I am fever']),
                'correct_answers' => json_encode(['I have a fever']),
                'hint' => 'How to say you have a fever',
                'position' => 15,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 3][Advanced] Translate to English: "Saya perlu pergi ke dokter"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['I need to go to the doctor', 'I need to see a doctor']),
                'hint' => 'Use the word "need" for a need and "doctor" for a doctor',
                'position' => 16,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 3] What is the English word for "alergi"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Allergy', 'Infection', 'Injury', 'Rash']),
                'correct_answers' => json_encode(['Allergy']),
                'hint' => 'A bodily reaction to specific substances',
                'position' => 17,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 3] Translate to English: "Saya membutuhkan obat"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['I need medicine', 'I need medication']),
                'hint' => 'Use the word "need" for a need and "medicine" for medicine',
                'position' => 18,
                'is_advanced' => false,
            ],

            // Part 4: Chronic Conditions (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4][Advanced] What is the English word for "tekanan darah tinggi"?',
                'prompt_type' => 'text',
                'options' => json_encode(['High blood pressure', 'Blood disease', 'Heart problem', 'Blood condition']),
                'correct_answers' => json_encode(['High blood pressure']),
                'hint' => 'The condition of blood pressure above normal',
                'position' => 19,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 4][Advanced] Translate to English: "Diabetes"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Diabetes']),
                'hint' => 'The disease related to blood sugar',
                'position' => 20,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4] What is the English word for "asma"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Asthma', 'Bronchitis', 'Pneumonia', 'Cough']),
                'correct_answers' => json_encode(['Asthma']),
                'hint' => 'The condition of difficulty breathing',
                'position' => 21,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 4][Advanced] Translate to English: "Radang sendi"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Arthritis']),
                'hint' => 'Inflammation in the joint',
                'position' => 22,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 4] Which is correct for "migrain"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Migraine', 'Headache', 'Brain pain', 'Head pain']),
                'correct_answers' => json_encode(['Migraine']),
                'hint' => 'The severe headache',
                'position' => 23,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 4][Advanced] Translate to English: "Kolesterol tinggi"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['High cholesterol']),
                'hint' => 'The condition of excess fat in the blood',
                'position' => 24,
                'is_advanced' => true,
            ],

            // Part 5: Treatment & Medicine (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5] What is the English word for "obat"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Medicine', 'Drug', 'Pill', 'Tablet']),
                'correct_answers' => json_encode(['Medicine']),
                'hint' => 'The substance for treating an illness',
                'position' => 25,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 5][Advanced] Translate to English: "Minum obat"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Take medicine', 'Take medication']),
                'hint' => 'The activity of taking medicine',
                'position' => 26,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5] Which is correct for "perban"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Bandage', 'Tape', 'Cloth', 'Wrap']),
                'correct_answers' => json_encode(['Bandage']),
                'hint' => 'The tool for covering a wound',
                'position' => 27,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 5][Advanced] Translate to English: "Resep dokter"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Prescription', 'Doctor\'s prescription']),
                'hint' => 'The letter from the doctor for getting medicine',
                'position' => 28,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 5] What is the English word for "plester"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Band-aid', 'Tape', 'Patch', 'Sticker']),
                'correct_answers' => json_encode(['Band-aid']),
                'hint' => 'The small wound cover',
                'position' => 29,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 5][Advanced] Translate to English: "Pemeriksaan kesehatan"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Medical check-up', 'Health examination']),
                'hint' => 'The process of checking health condition',
                'position' => 30,
                'is_advanced' => true,
            ],

            // Part 6: Emergency Situations (6 questions)
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6][Advanced] What is the English word for "kecelakaan"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Accident', 'Emergency', 'Incident', 'Crisis']),
                'correct_answers' => json_encode(['Accident']),
                'hint' => 'The unexpected event',
                'position' => 31,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Panggil ambulans"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Call an ambulance', 'Call the ambulance']),
                'hint' => 'Request medical assistance',
                'position' => 32,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6] Which is correct for "luka"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Wound', 'Cut', 'Injury', 'Hurt']),
                'correct_answers' => json_encode(['Wound']),
                'hint' => 'The injury on the body',
                'position' => 33,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Pertolongan pertama"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['First aid']),
                'hint' => 'First aid',
                'position' => 34,
                'is_advanced' => true,
            ],
            [
                'lesson_id' => 2,
                'type' => 'multiple_choice',
                'prompt' => '[Part 6] What is the English word for "patah tulang"?',
                'prompt_type' => 'text',
                'options' => json_encode(['Broken bone', 'Fracture', 'Bone injury', 'Bone damage']),
                'correct_answers' => json_encode(['Broken bone', 'Fracture']),
                'hint' => 'The condition of a bone that is separated',
                'position' => 35,
                'is_advanced' => false,
            ],
            [
                'lesson_id' => 2,
                'type' => 'translation',
                'prompt' => '[Part 6][Advanced] Translate to English: "Ruang gawat darurat"',
                'prompt_type' => 'text',
                'options' => null,
                'correct_answers' => json_encode(['Emergency room', 'ER']),
                'hint' => 'The room for urgent condition in the hospital',
                'position' => 36,
                'is_advanced' => true,
            ],
        ];

        // Combine all questions - only include lessons 1 and 2
        $allQuestions = array_merge(
            $questionsLesson1,
            $questionsLesson2
        );

        // Create questions in database
        foreach ($allQuestions as $question) {
            Question::create($question);
        }
    }
}
